### ISSUE TITLE
Automated tests for snippets/completion items

### ISSUE THREAD

**Issue by kathrynkodama** [eclipse/lsp4jakarta#304]
Determine whether these tests should be in the jakarta.ls or jakarta.jdt component

**Comment by TrevCraw** [comment]
The goal of this issue is to add tests covering all the snippets provided by jakarta.ls. These tests may be best suited in the existing jakarta.jdt test framework at https://github.com/eclipse/lsp4jakarta/tree/main/jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test or may need to be added to a new test framework as part of https://github.com/eclipse/lsp4jakarta/tree/main/jakarta.ls. It may be worth investigating what the LSP4MP project has at https://github.com/eclipse/lsp4mp/tree/master/microprofile.ls/org.eclipse.lsp4mp.ls/src/test. 

The following snippets should be covered:

[Jakarta Bean Validation snippets](https://github.com/eclipse/lsp4jakarta/blob/main/jakarta.ls/src/main/resources/bean-validation.json).

| Snippet prefix | Description |
| --------- | ------------ |
| @Email | Email address constraint, which validates a well-formed email address |

[Jakarta Persistence snippets](https://github.com/eclipse/lsp4jakarta/blob/main/jakarta.ls/src/main/resources/persistence.json).

| Snippet prefix | Description |
| --------- | ------------ |
| persist_context | Entity manager injection and associated persistence context |
| persist_context_extended | Entity manager injection with extended persistence context |
| persist_context_extended_unsync | Entity manager injection with extended, unsynchronized persistence context |
| persist_entity | Generic persistence entity model |

[Jakarta RESTful Web Services snippets](https://github.com/eclipse/lsp4jakarta/blob/main/jakarta.ls/src/main/resources/restfulWs.json).

| Snippet prefix | Description |
| --------- | ------------ |
| rest_class | Resource class with GET resource method |
| rest_get | GET resource method |
| rest_post | POST resource method |
| rest_put | PUT resource method |
| rest_delete | DELETE resource method |
| rest_head | HEAD resource method |

[Jakarta Servlet snippets](https://github.com/eclipse/lsp4jakarta/blob/main/jakarta.ls/src/main/resources/servlet.json).

| Snippet prefix | Description |
| --------- | ------------ |
| servlet_generic | Generic protocol independent servlet |
| servlet_doget | HTTPServlet with GET request |
| servlet_dopost | HTTPServlet with POST request |
| servlet_webfilter | Servlet WebFilter |

[Jakarta Transactions snippets](https://github.com/eclipse/lsp4jakarta/blob/main/jakarta.ls/src/main/resources/transactions.json).

| Snippet prefix | Description |
| --------- | ------------ |
| tx_user_inject | Initializes a UserTransaction object via injection |
| tx_user_jndi | Initializes a UserTransaction object via JNDI lookup |
| @ Transactional | Transactional annotation with rollbackOn and dontRollbackOn |

**Comment by aparnamichael** [comment]
We have gone through the lsp4mp, we found that the snippet test cases were implemented within the ls component. So, we decided to adopt the same approach. In order to verify the presence of snippets in the snippet registry, we have included test cases similar to the one's in lsp4mp.

**Comment by turkeylurkey** [comment]
aparnamichael is listed as a contributor but vaisakhkannan not yet.
