### ISSUE TITLE
Improving automated tests for diagnostics and quick-fixes

### ISSUE THREAD

**Issue by kathrynkodama** [eclipse/lsp4jakarta#305]
Identifying gaps in the current automated tests given #54 

The update uses fully qualified names so need to test if the package name is incorrect.

**Comment by TrevCraw** [comment]
The main goal of this issue is to create tests to verify we are using the fully qualified names to provide diagnostics.

Create new Java files in the [jakarta-sample project](https://github.com/eclipse/lsp4jakarta/tree/main/jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample) which contain fake package imports with Jakarta API package endings. For example, change the `jakarta.ws.rs.DELETE` package in [MultipleEntityParamsResourceMethod.java](https://github.com/eclipse/lsp4jakarta/blob/main/jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample/src/main/java/io/openliberty/sample/jakarta/jax_rs/MultipleEntityParamsResourceMethod.java) to `fake.ws.rs.DELETE`. 

The test should then verify that we do NOT provide a diagnostic on the `resourceMethodWithTwoEntityParams` method. Check the `org.eclipse.lsp4jakarta.jdt.core.JakartaForJavaAssert.*;` package to see if there are any methods that can help with confirming there is no diagnostic. If not, we may need to come up with a new method or strategy to check for no diagnostic.

**Comment by TrevCraw** [comment]
1)We should create new tests specifically just for checking for no diagnostics.
2) The test should attempt to grab a list of all the diagnostics in the "test project" file and confirm that the list of diagnostics is empty. There should not be any checks for specific diagnostics.
3) Create a new project with all the diagnostics that were previously using the "short name" check. This might apply for all diagnostics. It may be necessary to copy the entire existing test project and modify the package imports. It is OK if the new project does not compile.
4) Loop the new test checking for no diagnostics to run against every file in the new test project.
