### ISSUE TITLE
[VS Code] Quick-fix fails due to getData() is null

### ISSUE THREAD

**Issue by kathrynkodama** [eclipse/lsp4jakarta#416]
**To reproduce**
Using [jakarta-sample](https://github.com/eclipse/lsp4jakarta/tree/main/jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/projects/jakarta-sample) project in VS Code (Mac OS), trying to trigger quick-fixes on bean validation constraint diagnostics: 

```
[Error - 12:57:13 PM] Request textDocument/codeAction failed.
  Message: Request jakarta/java/codeaction failed with message: java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "org.eclipse.lsp4j.Diagnostic.getData()" is null
  Code: -32603 
```

<img width="1360" alt="image" src="https://user-images.githubusercontent.com/26146482/208489983-588f1845-9fec-48fe-92d2-a012b9e3bfa1.png">

**Comment by kathrynkodama** [comment]
Encountered the same bug on Dependency Injection diagnostics, this quick-fix does not appear:
https://github.com/eclipse/lsp4jakarta/blob/main/jakarta.jdt/org.eclipse.lsp4jakarta.jdt.core/src/main/java/org/eclipse/lsp4jakarta/jdt/core/di/ConflictInjectMultipleConstructorQuickFix.java

```
[Error - 1:30:22 PM] Request textDocument/codeAction failed.
  Message: Request jakarta/java/codeaction failed with message: java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "org.eclipse.lsp4j.Diagnostic.getData()" is null
  Code: -32603 
```

**Comment by kathrynkodama** [comment]
Same error reported Jsonb Diagnostics, see this class for the expected quick fixes: https://github.com/eclipse/lsp4jakarta/blob/main/jakarta.jdt/org.eclipse.lsp4jakarta.jdt.test/src/main/java/org/eclipse/lsp4jakarta/jdt/jsonb/JsonbDiagnosticsCollectorTest.java

**Comment by turkeylurkey** [comment]
Opened issue:
https://github.com/microsoft/vscode/issues/181166

**Comment by TrevCraw** [comment]
@dshimo recorded hitting this issue in #460

**Comment by turkeylurkey** [comment]
Affects diagnostics that use:
-ScopeDeclarationQuickFix
-BeanValidationQuickFix
-JsonbTransientAnnotationQuickFix
-ManagedBeanConstructorQuickFix
-ManagedBeanQuickFix
-PersistenceAnnotationQuickFix
-CompleteFilterAnnotationQuickFix
-CompleteServletAnnotationQuickFix

**Comment by aparnamichael** [comment]
We are using the custom request `Jakarta/Java/CodeAction` to handle code actions, and the `Workspace/executeCommand` is used to send the custom request to the LS. In Jakarta LS we are receiving the request with value in the ‘data’ parameter. But Jakarta LS expects a Map object from VS Code, but we are sending a string or array of strings from VS code. 

eg:
data = “AssertTrue”
data =[“ApplicationScoped", "RequestScoped”]

**lsp4Jakarta code**
` /**
   * Returns the child as a JsonObject if it exists and is an object, and null
   * otherwise
   *
   * @param obj the object to get the child of
   * @param key the key of the child
   * @return the child as a JsonObject if it exists and is an object, and null
   *     otherwise
   */
  public static JsonObject getObjectAsJson(Map<String, Object> obj, String key) {
    Object child = obj.get(key);

    LOGGER.info(" object for " + key + "value = " + child.toString());

    if (child != null && child instanceof Map<?, ?>) {
      Gson gson = new Gson();
      return (JsonObject) gson.toJsonTree(child);
    }
    return null;
  }
}`


Resolved the null pointer exception by adding code to handle both the 'data' format.
